name: Pipeline
on: [push]

jobs:
    pycicd:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Pytest
          uses: ./
          with:
            run_type: pytest
            args: -h
          env:
            LOG_LEVEL: DEBUG
        - name: Black
          uses: ./
          with:
            run_type: black
          env:
            LOG_LEVEL: DEBUG
